//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciNotSistemiMVC.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbMvcOkulEntities : DbContext
    {
        public DbMvcOkulEntities()
            : base("name=DbMvcOkulEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OgrenciLogin> OgrenciLogins { get; set; }
        public virtual DbSet<TBL_DERSLER> TBL_DERSLER { get; set; }
        public virtual DbSet<TBL_KULUPLER> TBL_KULUPLER { get; set; }
        public virtual DbSet<TBL_NOTLAR> TBL_NOTLAR { get; set; }
        public virtual DbSet<TBL_OGRENCILER> TBL_OGRENCILER { get; set; }
        public virtual DbSet<tblCanliDersler> tblCanliDerslers { get; set; }
        public virtual DbSet<TBL_OGRENCIGIRIS> TBL_OGRENCIGIRIS { get; set; }
        public virtual DbSet<TBL_ONLINE_DERSLER> TBL_ONLINE_DERSLER { get; set; }
        public virtual DbSet<TBL_OGRETMENGIRIS> TBL_OGRETMENGIRIS { get; set; }
    }
}
