//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciNotSistemiMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgrenciLogin
    {
        public byte OGRENCIID { get; set; }
        public string OGRENCIISMI { get; set; }
        public string OGRENCISOYISMI { get; set; }
        public string OGRENCINUMARASI { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<bool> AKTIFMI { get; set; }
    }
}
