//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciNotSistemiMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_OGRENCIGIRIS
    {
        public int OGRENCIID { get; set; }
        public string OGRENCIAD { get; set; }
        public string OGRENCISOYAD { get; set; }
        public string OGRENCIFOTOGRAF { get; set; }
        public string OGRENCICINSIYET { get; set; }
        public Nullable<int> OGRENCIKULUP { get; set; }
        public string OGRENCINO { get; set; }
        public string SIFRE { get; set; }
    }
}
