//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciNotSistemiMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ONLINE_DERSLER
    {
        public int ID { get; set; }
        public string DersAdi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> BaslangicTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public string MeetingLink { get; set; }
        public string VideoUrl { get; set; }
    }
}
