//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciNotSistemiMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_OGRETMENGIRIS
    {
        public int ID { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
        public string AdSoyad { get; set; }
        public string EMail { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
