//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciNotSistemiMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCanliDersler
    {
        public byte CANLIDERSID { get; set; }
        public Nullable<byte> DERSID { get; set; }
        public string OGRETMENAD { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string SAAT { get; set; }
        public string LINK { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
    }
}
